DemoDay/Models/TimeSlot.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoDay.Models
{
    public class TimeSlot
    {
        public int Id { get; set; }

        public DateTime StartTime { get; set; }

        public DateTime EndTime { get; set; }
    }
}

DemoDay/Controllers/TimeSlotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DemoDay.Data;
using DemoDay.Models;
using DemoDay.Models.ReportItems;

namespace DemoDay.Controllers
{
    public class TimeSlotsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TimeSlotsController(ApplicationDbContext context)
        {
            _context = context;
        }

        private bool StudentIsAvailable(Student student, TimeSlot time)
        {

            var scheduledInterviewsForStudent = _context.Interview.Where(i => i.Ranking.StudentId == student.Id).Include(i => i.TimeSlot).ToList();

            // Don't schedule more than five time slots per student
            if (scheduledInterviewsForStudent.Count() < 5)
            {
                var occupiedTimeSlotsForStudent = scheduledInterviewsForStudent.Select(i => i.TimeSlot);
                var openTimeSlotsForStudent = _context.TimeSlot.Where(ti => !occupiedTimeSlotsForStudent.Contains(ti));

                return openTimeSlotsForStudent.Contains(time);

            }
            return false;
        }

        private bool CompanyIsAvailable(Company company, TimeSlot time)
        {
            var scheduledInterviewsForCompany = _context.Interview.Where(i => i.Ranking.CompanyId == company.Id).Include(i => i.TimeSlot).ToList();
            var occupiedTimeSlotsForCompany = scheduledInterviewsForCompany.Select(i => i.TimeSlot);
            var availableTimeSlots = _context.CompanyAvailability.Where(c => c.CompanyId == company.Id).Select(ci => ci.TimeSlot).ToList();

            // Find the time slots when a) a company is generally available and b) they don't already have an interview scheduled
            var openTimeSlotsForCompany = _context.TimeSlot.Where(ti => !occupiedTimeSlotsForCompany.Contains(ti) && availableTimeSlots.Contains(ti));

            return openTimeSlotsForCompany.Contains(time);

        }

        // Returns true if an interview is already scheduled between a student and a company
        // Returns false if no interview has been scheduled
        private bool AlreadyScheduled(Student student, Company company)
        {
            var studentsInterviews = _context.Interview
                .Include(i => i.Ranking)
                    .ThenInclude(r => r.Company)
                .Where(i => i.Ranking.StudentId == student.Id)
                .ToList();

            var studentCompanies = studentsInterviews.Select(i => i.Ranking.Company);

            return studentCompanies.Contains(company);
        }

        private bool isLocationCompatible(Student student, Company company)
        {
            if (!company.isLocal)
            {
                return student.canRelocate;
            }

            return true;
        }

        private bool meetsRequirements(Student student, Company company)
        {
            if (company.requiresBachelorsDegree)
            {
                return student.hasBachelorsDegree;
            }

            return true;
        }

        private void scheduleInterview(Ranking rank, List<TimeSlot> allTimeSlots)
        {
           
            
            if (meetsRequirements(rank.Student, rank.Company) && !AlreadyScheduled(rank.Student, rank.Company))
            {
                var openSlot = allTimeSlots.FirstOrDefault(time => CompanyIsAvailable(rank.Company, time) && StudentIsAvailable(rank.Student, time));

                if (openSlot != null)
                {
                    var interview = new Interview()
                    {
                        TimeSlotId = openSlot.Id,
                        TimeSlot = openSlot,
                        RankingId = rank.Id,
                        Ranking = rank
                    };
                    _context.Add(interview);
                    _context.SaveChanges();

                }

            }
        }

        public async Task<IActionResult> ScheduleIndex(string sortBy)
        {
            // Wipe out the original interviews, we're going to generate new ones
            _context.Interview.RemoveRange(_context.Interview);

            await _context.SaveChangesAsync();

            // delete this later, this is just for testing
            var allInterviews = await _context.Interview.ToListAsync();

            // Todo: change cohort dynamically
            var rankings = await _context.Ranking
                .Include(r => r.Student)
                .Include(r => r.Company)
                .OrderBy(r => r.Company.Name)
                .ThenBy(r => r.Rank)
                .ToListAsync();

            var groupedRankings = (from r in rankings
                                   group r by r.Company.Name into gr
                                   select new CompanyList()
                                   {
                                       Company = gr.ToList()[0].Company,
                                       PriorityRankings = gr.OrderBy(r => r.Rank).ToList()
                                   }).OrderByDescending(cl => cl.Company.Name).ToList();


            var allTimeSlots = await _context.TimeSlot.ToListAsync();
            groupedRankings.ForEach(gr =>
            {
                // TODO: make async? 
                // TODO: dry this up
                // Get available time blocks for company


                // Loop through students who priortized that company first and, in order, try to assign them to an interview
                gr.PriorityRankings.ForEach(r =>
                {
                    if (r.Rank == 1)
                    {
                        scheduleInterview(r, allTimeSlots);
                    }

                });
                gr.PriorityRankings.ForEach(r =>
                {
                    // Find the first time when they're both available
                    if (r.Rank == 2)
                    {
                        scheduleInterview(r, allTimeSlots);

                    }

                });


                // Loop through students who priortized that company first and, in order, try to assign them to an interview
                gr.PriorityRankings.ForEach(r =>
                {
                    // Find the first time when they're both available
                    if (r.Rank == 3)
                    {
                        scheduleInterview(r, allTimeSlots);

                    }

                });


                // Loop through students who priortized that company first and, in order, try to assign them to an interview
                gr.PriorityRankings.ForEach(r =>
                {
                    // Find the first time when they're both available
                    if (r.Rank == 4)
                    {
                        scheduleInterview(r, allTimeSlots);
                    }

                });


                // Loop through students who priortized that company first and, in order, try to assign them to an interview
                gr.PriorityRankings.ForEach(r =>
                {
                    // Find the first time when they're both available
                    if (r.Rank == 5)
                    {
                        scheduleInterview(r, allTimeSlots);
                    }

                });

            });



            var newInterviews = await _context.Interview
               .Include(i => i.TimeSlot)
               .Include(i => i.Ranking)
                   .ThenInclude(r => r.Student)
               .Include(i => i.Ranking)
                   .ThenInclude(r => r.Company)
               .ToListAsync();

            var newInterviewsGroupedByCompany = (from i in newInterviews
                                                 group i by i.Ranking.Company.Name into gi
                                                 select new CompanyList()
                                                 {
                                                     Company = gi.ToList()[0].Ranking.Company,
                                                     InterviewSchedule = gi.OrderBy(i => i.TimeSlot.StartTime).ToList()
                                                 }).OrderBy(cl => cl.InterviewSchedule.Count()).ToList();

            var newInterviewsGroupedByStudent = (from i in newInterviews
                                                 group i by i.Ranking.Student.FirstName into gi
                                                 select new CompanyList()
                                                 {
                                                     Student = gi.ToList()[0].Ranking.Student,
                                                     InterviewSchedule = gi.OrderBy(i => i.TimeSlot.StartTime).ToList()
                                                 }).OrderBy(sl => sl.InterviewSchedule.Count()).ThenBy(sl => sl.Student.FirstName).ToList();


            

            newInterviewsGroupedByCompany.ForEach(c =>
            {
                if (c.InterviewSchedule.Count() < 5)
                {

                    // Loop through all the time slots
                    _context.TimeSlot.ToList().ForEach(time =>
                    {
                        // If the company is available in that time slot
                        if (CompanyIsAvailable(c.Company, time))
                        {
                            

                            var firstAvailableStudent = newInterviewsGroupedByStudent.FirstOrDefault(s =>
                            StudentIsAvailable(s.Student, time) &&
                            !AlreadyScheduled(s.Student, c.Company) &&
                            meetsRequirements(s.Student, c.Company) &&
                            isLocationCompatible(s.Student, c.Company));
                            if (firstAvailableStudent != null)
                            {

DemoDay/Views/TimeSlots/Create.cshtml
@model DemoDay.Models.TimeSlot

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TimeSlot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoDay/Views/TimeSlots/Delete.cshtml
@model DemoDay.Models.TimeSlot

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TimeSlot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoDay/Views/TimeSlots/Details.cshtml
@model DemoDay.Models.TimeSlot

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TimeSlot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DemoDay/Views/TimeSlots/Edit.cshtml
@model DemoDay.Models.TimeSlot

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TimeSlot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoDay/Views/TimeSlots/Index.cshtml
@model IEnumerable<DemoDay.Models.TimeSlot>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DemoDay/Views/TimeSlots/ScheduleIndex.cshtml
@model IEnumerable<DemoDay.Models.ReportItems.CompanyList>
<h1>Schedule Manager</h1>

<a class="btn btn-primary" asp-action="Index" asp-controller="TimeSlots">Manage Time Slots</a>

<a class="btn btn-success" asp-action="ScheduleIndex" asp-controller="TimeSlots" asp-route-sortBy="student">View Student Schedule</a>
<a class="btn btn-success" asp-action="ScheduleIndex" asp-controller="TimeSlots" asp-route-sortBy="company">View Company Schedule</a>
<a class="btn btn-success" asp-action="ScheduleIndex" asp-controller="TimeSlots" asp-route-sortBy="timeSlot">View Master Schedule</a>



<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            var numberOfInterviews = item.InterviewSchedule.Count();
            if (item.Company != null)
            {

                <div class="card col-sm-5 m-2">

                    <h4 class=" card-header text-lg-center">@Html.DisplayFor(m => item.Company.Name)</h4>
                    <div class="card-body">
                        <p class="text-sm-center">Number of Interviews: @numberOfInterviews</p>
                        @foreach (var interview in item.InterviewSchedule)
                        {
                            var startTime = interview.TimeSlot.StartTime.ToShortTimeString();
                            var endTime = interview.TimeSlot.EndTime.ToShortTimeString();
                            <p class="font-weight-bold text-success">@Html.DisplayFor(m => interview.Ranking.Student.FirstName)</p>

                            <p class="font-weight-light">Ranking: @Html.DisplayFor(m => interview.Ranking.Rank)</p>
                            <p>@Html.DisplayFor(m => startTime) - @Html.DisplayFor(m => endTime)</p>

                        }

                    </div>
                </div>

            }
            else if (item.Student != null)
            {
                <div class="card col-sm-5 m-2">

                    <h4 class="card-header text-lg-center">@Html.DisplayFor(m => item.Student.FirstName)</h4>


                    <div class="card-body">
                        <p class="text-sm-center">Number of Interviews: @numberOfInterviews</p>
                        @foreach (var interview in item.InterviewSchedule)
                        {
                            var startTime = interview.TimeSlot.StartTime.ToShortTimeString();
                            var endTime = interview.TimeSlot.EndTime.ToShortTimeString();
                            <p class="font-weight-bold text-success">@Html.DisplayFor(m => interview.Ranking.Company.Name)</p>
                            <p class="font-weight-light">Ranking: @Html.DisplayFor(m => interview.Ranking.Rank)</p>
                            <p>@Html.DisplayFor(m => startTime) - @Html.DisplayFor(m => endTime)</p>

                        }
                    </div>


                </div>

            }
            else
            {
                <div class="card card col-sm-5 m-2">

                    @{var startTime = item.TimeSlot.StartTime.ToShortTimeString();}
                    @{var endTime = item.TimeSlot.EndTime.ToShortTimeString();}
                    <h4 class="text-lg-center card-header">@Html.DisplayFor(m => startTime) - @Html.DisplayFor(m => endTime)</h4>

                    <div class="card-body">
                        @foreach (var interview in item.InterviewSchedule)
                        {

                            <p class="font-weight-bold text-success">@Html.DisplayFor(m => interview.Ranking.Student.FirstName) + @Html.DisplayFor(m => interview.Ranking.Company.Name)</p>
                            <p class="font-weight-light">Ranking: @Html.DisplayFor(m => interview.Ranking.Rank)</p>

                        }

                    </div>

                </div>



            }
        }

    </div>
</div>